spring:
  application:
    name: display
  freemarker:
    suffix: .ftl
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates/
    request-context-attribute: request
    expose-request-attributes: true
  mvc:
    favicon:
      enabled:true
    static-path-pattern: /static/**
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Application?useSSl=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mail:
    host: smtp.qq.com
    port: 465
    username: xxxxxx
    password: xxxxxx
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls:
            enable: true



